# Generated by Django 5.0.7 on 2024-08-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='none', max_length=100)),
                ('msg', models.CharField(default='none', max_length=100)),
                ('pic', models.ImageField(upload_to='media/pics')),
                ('fee', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='post_blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('Title', models.CharField(max_length=100)),
                ('Image', models.ImageField(default='none', upload_to='media/pics')),
                ('Description', models.TextField(max_length=300)),
            ],
        ),
    ]
